# Generated by Django 5.0.6 on 2024-05-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourclass',
            old_name='desctiption',
            new_name='description',
        ),
    ]
